### PR TITLE
Add Service Manager functionality

### PR DESCRIPTION
**Pull request by sdnetwork**
List of function implemeted :

backup=> return stream
nbackup=> return stream
restore=> return stream
nrestore => return stream
fixpropertie  => return stream
serverinfo => return object
database validation => return stream
comit transact => return stream
rollback transact => return stream
recover transact => return stream
license ??? => return stream
database stats => return stream
users infos => return object
user actions // add modify remove => return stream
get fb file log => return stream
  
this is an exemple to use with stream and object

```javascript
fb.attach(_connection, function(err, svc) {	
	if (err)
		return;
	// all function that return a stream take two optional parameter
	// optread => byline or buffer	byline use isc_info_svc_line and buffer use isc_info_svc_to_eof
	// buffersize => is the buffer for service manager it can't exceed 8ko (i'm not sure)
		
	svc.getLog({optread:'buffer', buffersize:2048}, function (err, data) {
            // data is a readablestream that contain the firebird.log file
            console.log(err);
            data.on('data', function (data) {
                console.log(data.toString());
            });
			data.on('end', function() {
				console.log('finish');
			});
        });
		
	// an other exemple to use function that return object
	svc.getFbserverInfos(
            {
            "dbinfo" : true,
            "fbconfig" : true,
            "svcversion" : true,
            "fbversion" : true,
            "fbimplementation" : true,
            "fbcapatibilities" : true,
            "pathsecuritydb" : true,
            "fbenv" : true,
            "fbenvlock" : true,
            "fbenvmsg" : true
        }, {}, function (err, data) {
            console.log(err);
            console.log(data);
        });	
});
```

It stays a lot of test to do ;) but globally it works well.
the main function to stay to implement are :

1) trace
2) limbo

### CODE REVIEW

**Comment by mariuz** [comment]
Thank you 

license was from the time when interbase/firebird was propietary

**Comment by sdnetwork** [comment]
Ok i remove it, i continue by this way  to put change (pull request) ? i ask that because  i will do a lot of little modification, maybe there is an other solution with git (i don't know very well it)

**Comment by mapopa** [comment]
you can send a pull request 

also i have asked henry to add you to contributors

**Comment by elgubenis** [comment]
i get svc undefined, my console.log gives this: 
screen shot 2015-10-25 at 13 33 57

**Comment by elgubenis** [comment]
found out that i need to add manager: true in the options, thanks!!!

**Pull request merged**
